---
- name: Configure host.
  hosts: localhost
  connection: local
  vars_files:
    - vars/hardware_settings.yaml
    - vars/shell_packages.yaml
  roles:
    - homebrew
    - shell
    - zsh
    - office_tools
    - dev
    - cloud_providers
    - kubernetes
    - openshift
