---
- name: Install Powerlevel10k for macOS
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - powerlevel10k
  register: result
  until: result is successful
  when: "(homebrew_check_x86_64.stat.exists | default(false) or homebrew_check_arm64.stat.exists | default(false))"

- name: Display Homebrew Packages result
  ansible.builtin.debug:
    msg: "{{ result }}"
