---
- name: Check CPU chip architecture for arm64 or x86_64
  ansible.builtin.command: /usr/bin/uname -m
  changed_when: false
  register: cpu_arch_output

- name: Display CPU architecture
  ansible.builtin.debug:
    var: cpu_arch_output.stdout

- name: Set CPU architecture variable
  ansible.builtin.set_fact:
    cpu_arch: '{{ cpu_arch_output.stdout }}'
  when: "'x86_64' in cpu_arch_output.stdout"

- name: Check if Homebrew is installed on x86_64
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: homebrew_check_x86_64
  when: cpu_arch == 'x86_64'

- name: Check if Homebrew is installed on arm64
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check_arm64
  when: cpu_arch == 'arm64'

- name: Display Homebrew check for x86_64
  ansible.builtin.debug:
    var: homebrew_check_x86_64
  when: cpu_arch == 'x86_64'

- name: Display Homebrew check for arm64
  ansible.builtin.debug:
    var: homebrew_check_arm64
  when: cpu_arch == 'arm64'


# On ARM macOS, this script installs to /opt/homebrew only
# On Intel macOS, this script installs to /usr/local only
- name: Installing Homebrew
  ansible.builtin.shell: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  when:
    - "not (homebrew_check_x86_64.stat.exists | default(false) and homebrew_check_arm64.stat.exists | default(false))"
  register: brew_install

- name: Display Homebrew installation
  ansible.builtin.debug:
    msg: "{{ which_brew.stdout }}"


- name: Run 'which brew' command
  changed_when: false
  ansible.builtin.command: which brew
  ignore_errors: true
  register: which_brew

- name: Display where 'brew' is installed
  ansible.builtin.debug:
    msg: "'brew' is installed to: {{ which_brew.stdout }}"

- name: Run 'brew --version' command
  changed_when: false
  ansible.builtin.command: brew --version
  ignore_errors: true
  register: brew_version

- name: Display which version of 'brew' is installed
  ansible.builtin.debug:
    msg: "'brew' is installed with version: {{ brew_version.stdout }}"
