---
- name: Check if Homebrew is installed on x86_64
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: homebrew_check_x86_64
  when: cpu_arch == 'x86_64'

- name: Check if Homebrew is installed on arm64
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check_arm64
  when: cpu_arch == 'arm64'

- name: Install Visual Studio Code for macOS
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
  register: result
  until: result is successful
  when: "(homebrew_check_x86_64.stat.exists | default(false) or homebrew_check_arm64.stat.exists | default(false))"

- name: Display Homebrew Cask Packages result
  ansible.builtin.debug:
    msg: "{{ result }}"
