---
name: CI
'on':   # Single quotes for yamllint
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:   # Schedule for every 10th of a month at 5AM
    - cron: '0 5 10 * *'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10.12'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible ansible-lint

      - name: Lint code with yamllint.
        run: |
          yamllint .

      - name: Lint code with ansible-lint.
        run: |
          ansible-lint

  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-12  # monterey
          - macos-13  # ventura
          # - macos-14  # sonoma

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Uninstall GitHub Actions' built-in Homebrew.
        run: tests/uninstall-homebrew.sh

      - name: Uninstall GitHub Actions' built-in browser installs.
        run: |
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app
          sudo rm -rf /usr/local/bin/firefox

      - name: Test the playbook.
        run: make run
        env:
          ANSIBLE_FORCE_COLOR: '1'
